version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /packages/toolbox
      - /plugins/palette
      - /plugins/basic
    schedule:
      interval: daily
    groups:
      framer:
        patterns:
          - '*'
    allow:
      - dependency-name: framer-plugin
      - dependency-name: framer-motion
      - dependency-name: vite-plugin-framer
