version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /packages/toolbox
    schedule:
      interval: daily
    groups:
      toolbox:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@typescript-eslint/*'
        update-types: [version-update:semver-major]
      - dependency-name: eslint
        update-types: [version-update:semver-major]

  - package-ecosystem: npm
    directories:
      - /plugins/palette
    schedule:
      interval: daily
    groups:
      palette:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@typescript-eslint/*'
        update-types: [version-update:semver-major]
      - dependency-name: eslint
        update-types: [version-update:semver-major]

  - package-ecosystem: npm
    directories:
      - /plugins/basic
    schedule:
      interval: daily
    groups:
      basic:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@typescript-eslint/*'
        update-types: [version-update:semver-major]
      - dependency-name: eslint
        update-types: [version-update:semver-major]
